var a = [
  {ch:"〇", val:0},
  {ch:"零", val:0},
  {ch:"0", val:0},
  {ch:"０", val:0},
  {ch:"一", val:1},
  {ch:"壱", val:1},
  {ch:"弌", val:1},
  {ch:"壹", val:1},
  {ch:"1", val:1},
  {ch:"１", val:1}, 
  {ch:"二", val:2},
  {ch:"弐", val:2},
  {ch:"貮", val:2},
  {ch:"貳", val:2},
  {ch:"2", val:2},
  {ch:"２", val:2},
  {ch:"三", val:3},
  {ch:"参", val:3},
  {ch:"參", val:3},
  {ch:"3", val:3},
  {ch:"３", val:3},
  {ch:"四", val:4},
  {ch:"肆", val:4},
  {ch:"4", val:4},
  {ch:"４", val:4},
  {ch:"五", val:5},
  {ch:"伍", val:5},
  {ch:"5", val:5},
  {ch:"５", val:5},
  {ch:"六", val:6},
  {ch:"陸", val:6},
  {ch:"6", val:6},
  {ch:"６", val:6}, 
  {ch:"七", val:7},
  {ch:"漆", val:7},
  {ch:"7", val:7},
  {ch:"７", val:7},
  {ch:"八", val:8},
  {ch:"捌", val:8},
  {ch:"8", val:8},
  {ch:"８", val:8},
  {ch:"九", val:9},
  {ch:"玖", val:9},
  {ch:"9", val:9},
  {ch:"９", val:9},
];

var b = [
  {ch:"十", val:1},
  {ch:"拾", val:1},
  {ch:"什", val:1},
  {ch:"百", val:2},
  {ch:"陌", val:2},
  {ch:"佰", val:2},
  {ch:"千", val:3},
  {ch:"阡", val:3},
  {ch:"仟", val:3},
];

var c = [
  {ch:"万", val:1},
  {ch:"萬", val:1},
  {ch:"億", val:2},
  {ch:"兆", val:3},
  {ch:"京", val:4},
  {ch:"垓", val:5},
  {ch:"𥝱", val:6},
  {ch:"穰", val:7},
  {ch:"溝", val:8},
  {ch:"澗", val:9},
  {ch:"正", val:10},
  {ch:"載", val:11},
  {ch:"極", val:12},
  {ch:"恒河沙", val:13},
  {ch:"阿僧祇", val:14},
  {ch:"那由他", val:15},
  {ch:"不可思議", val:16},
  {ch:"無量大数", val:17},
];
